require 'ruby-enum'

class TrxStatus
  include Ruby::Enum

  # IN_CONFIRMED: 转入已确认，可以执行后续的转出操作
  initialized = const_get('TrxStatus::NEW') rescue nil
  initialized.nil? && %W(
  NEW

  IN_CONFIRMED

  AUTO_OUT_PROCESSING
  AUTO_OUT_PROCESSED
  AUTO_OUT_CONFIRMED
  AUTO_OUT_ERR_BAD_ADDRESS
  AUTO_OUT_ERR_GW_DISABLED
  AUTO_OUT_ERR_OUT_TO_GW
  AUTO_OUT_ERR_ASSET_UNKNOWN
  AUTO_OUT_ERR_ASSET_DISABLED
  AUTO_OUT_ERR_OUT_CHAIN_DISABLED
  AUTO_OUT_ERR_OUT_CHAIN_NOT_FOUND
  AUTO_OUT_ERR_OUT_CHAIN_NOT_RELIABLE
  AUTO_OUT_ERR_OUT_FROM_ACCOUNT_NOT_FOUND
  AUTO_OUT_ERR_OUT_FROM_ACCOUNT_DISABLED
  AUTO_OUT_ERR_INSUFFICIENT_BALANCE
  AUTO_OUT_ERR_AMOUNT_LARGE_THAN_IN
  AUTO_OUT_ERR_UNKNOWN


  MANUAL_OUT_PROCESSING
  MANUAL_OUT_PROCESSED
  MANUAL_OUT_CONFIRMED
  MANUAL_OUT_ERR_OUT_DISABLED
  MANUAL_OUT_ERR_OUT_FROM_ACCOUNT_NOT_FOUND
  MANUAL_OUT_ERR_OUT_FROM_ACCOUNT_DISABLED
  MANUAL_OUT_ERR_INSUFFICIENT_BALANCE
  MANUAL_OUT_ERR_AMOUNT_LARGE_THAN_IN
  MANUAL_OUT_UNKNOWN


  IN_ERR_MEMO_EMPTY
  IN_ERR_MEMO_TOO_LONG
  IN_ERR_MEMO_BAD_FORMAT
  IN_ERR_MEMO_GATEWAY_UNKNOWN
  IN_ERR_MEMO_PLATFORM_UNKNOWN
  IN_ERR_MEMO_ASSET_DISABLED
  IN_ERR_MEMO_ASSET_UNKNOWN
  IN_ERR_AMOUNT_TOO_LITTLE
  IN_ERR_ETH_NOT_BIND
  IN_ERR_ERC20_NOT_BIND
  IN_ERR_BTC_NOT_BIND
  IN_ERR_OMNI_NOT_BIND
  IN_ERR_UNKNOWN
 ).each {|k|
    define k.to_sym, k.to_s.downcase
  }
end